POST http://localhost:8000/api/ambassador/register
Content-Type: application/json

{
  "first_name": "im ambassador bro",
  "last_name": "yes i am",
  "email": "ambassador@gmail.com",
  "password": "123123",
  "password_confirm": "123123"
}

###

POST http://localhost:8000/api/ambassador/login
Content-Type: application/json

{
 "email": "ambassador@gmail.com",
  "password": "123123"
}

###

POST http://localhost:8000/api/admin/login
Content-Type: application/json

{
 "email": "cagriroborboro@gmail.com",
  "password": "123123"
}

###

POST http://localhost:8000/api/admin/logout

###

GET http://localhost:8000/api/admin/user

###

PUT http://localhost:8000/api/admin/user
Content-Type: application/json

{
   "first_name": "cagrito",
   "password": "123123",
   "confirm_password": "1d23123"
}


